field: f7f5703c-a5d1-4ece-81f6-cd69aacba8cb
fieldLayouts:
  b8ebab1f-4c19-49a3-b626-7262a082aecd:
    tabs:
      -
        elements:
          -
            fieldUid: 6884bf14-6cfc-4f23-ac2f-3702687f8602
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6884bf14-6cfc-4f23-ac2f-3702687f8602:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heading
name: Heading
sortOrder: 1
