defaultPlacement: end
enableVersioning: true
handle: products
name: Products
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: none
siteSettings:
  280fceb8-a5d2-4c0b-9ee5-1ab5d6de749b:
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 'other/products/{slug}'
  353b994a-9997-4f98-b31f-a963cf7671f8:
    enabledByDefault: true
    hasUrls: true
    template: products/_entry
    uriFormat: 'products/{slug}'
type: channel
